services:
  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app

  app:
    build: ./app
    container_name: devops-app
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_USER: devops
      POSTGRES_PASSWORD: devops
      POSTGRES_DB: devopsdb
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: